Move env.sh functionality to action.yml
The logic from the env.sh script is migrated directly into the GitHub Actions workflow file, action.yml. This change simplifies the workflow by eliminating the need for an independent script file and integrates the environment configuration directly into the CI/CD process. The PATH_TO_CERTIFICATE variable is also adjusted to directly use the input certificates.

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -21,7 +21,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       PATH_TO_ENV: "${{ inputs.country }}/${{ inputs.environment }}"
-      PATH_TO_CERTIFICATE: "${{ inputs.country }}/${{ inputs.environment }}/certificates"
+      PATH_TO_CERTIFICATE: "${{ inputs.certificates }}"
       COUNTRY: "${{ inputs.country }}"
       ENVIRONMENT: "${{ inputs.environment }}"
     steps:
@@ -30,8 +30,19 @@ jobs:
 
       - name: Load Environment Configurations
         run: |
-          chmod +x scripts/env.sh
-          scripts/env.sh $PATH_TO_ENV/config.env
+          
+          ENV_FILE=$PATH_TO_ENV/config.env
+          
+          if [ ! -f "$ENV_FILE" ]; then
+              echo "File .env not found: $ENV_FILE"
+              exit 1
+          fi
+          while IFS= read -r line || [[ -n "$line" ]]; do
+              if [[ $line = \#* ]] || [ -z "$line" ]; then
+                  continue
+              fi
+              echo "$line" >> "$GITHUB_ENV"
+          done <"$ENV_FILE"
 
       - name: Verify Directory Structure and Configuration File
         run: |
